name: Continue Config
version: 1.0.0
schema: v1

models:
  - name: groq-llama
    provider: openai
    model: llama-3.3-70b-versatile
    apiBase: https://api.groq.com/openai/v1
    apiKey: "${{ secrets.GROQ_API_KEY }}"


systemMessage: |
  Tu es un expert en Astro, TypeScript, TailwindCSS et développement web moderne.
  Tu écris du code propre, typé, optimisé et facile à maintenir.
